# Generated by Django 4.2.7 on 2026-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_subscriptionplan_customuser_is_subscribed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Receive email notifications for news and updates",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="newsletter_subscription",
            field=models.BooleanField(
                default=True, help_text="Subscribe to newsletter"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="includes_email_notifications",
            field=models.BooleanField(
                default=True, help_text="Plan includes email notifications"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="includes_newsletter",
            field=models.BooleanField(
                default=True, help_text="Plan includes newsletter subscription"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
