# Generated by Django 4.2.7 on 2026-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features included in this plan (e.g., ["Advanced Analytics", "Priority Support", "Custom Reports"])'),
        ),
    ]
