# Generated by Django 4.2.7 on 2026-02-04 07:17

import apps.core.utils
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0005_alter_category_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2024 NewsHub. All rights reserved.",
                        help_text="Copyright text displayed in footer",
                        max_length=200,
                    ),
                ),
                (
                    "show_social",
                    models.BooleanField(
                        default=True, help_text="Display social media links in footer"
                    ),
                ),
                (
                    "extra_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Additional footer links as JSON array: [{"text": "Privacy", "url": "/privacy"}]',
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        blank=True,
                        help_text="Brief about text for footer",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer Settings",
                "verbose_name_plural": "Footer Settings",
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_title",
                    models.CharField(
                        default="NewsHub - Latest News & Updates",
                        help_text="Default page title (max 60 chars for SEO)",
                        max_length=60,
                    ),
                ),
                (
                    "default_description",
                    models.TextField(
                        default="Stay updated with the latest news, breaking stories, and in-depth analysis.",
                        help_text="Default meta description (max 160 chars for SEO)",
                        max_length=160,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Default meta keywords (comma-separated)",
                        max_length=255,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Default Open Graph image for social sharing",
                        null=True,
                        upload_to="seo/",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics tracking ID (e.g., G-XXXXXXXXXX)",
                        max_length=50,
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console verification code",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="SidebarWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Widget title displayed in sidebar", max_length=100
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Widget content (supports HTML)"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show this widget"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sidebar Widget",
                "verbose_name_plural": "Sidebar Widgets",
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="NewsHub",
                        help_text="Site name displayed in header and meta tags",
                        max_length=100,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Site logo (recommended: 200x50 to 1000x300 px)",
                        null=True,
                        upload_to=apps.core.utils.site_logo_upload_path,
                        validators=[apps.core.validators.validate_site_logo],
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Site favicon (recommended: 32x32 or 64x64 px)",
                        null=True,
                        upload_to=apps.core.utils.site_favicon_upload_path,
                        validators=[apps.core.validators.validate_favicon],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Site description for meta tags and about section",
                        max_length=500,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#e74c3c",
                        help_text="Primary brand color (hex format, e.g., #e74c3c)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("pinterest", "Pinterest"),
                            ("reddit", "Reddit"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                        ],
                        help_text="Social media platform",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Full URL to social media profile", max_length=500
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g., fab fa-facebook)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Display this social link"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="AdvertisementBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title for admin reference", max_length=100
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Advertisement banner image",
                        upload_to=apps.core.utils.ad_banner_upload_path,
                        validators=[apps.core.validators.validate_ad_banner],
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect when banner is clicked",
                        max_length=500,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("sidebar", "Sidebar"),
                            ("footer", "Footer"),
                            ("homepage", "Homepage"),
                            ("article_top", "Article Top"),
                            ("article_bottom", "Article Bottom"),
                        ],
                        help_text="Where to display this banner",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this advertisement"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within position (lower numbers first)",
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(
                        default=0, editable=False, help_text="Number of times displayed"
                    ),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0, editable=False, help_text="Number of clicks"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertisement Banner",
                "verbose_name_plural": "Advertisement Banners",
                "ordering": ["position", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["position", "is_active"],
                        name="core_advert_positio_237914_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("featured", "Featured Articles"),
                            ("trending", "Trending News"),
                            ("editorial", "Editorial Picks"),
                            ("category", "Category Showcase"),
                            ("video", "Video Section"),
                        ],
                        help_text="Type of homepage section",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Section title", max_length=100)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Optional subtitle or description",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Section background or featured image",
                        null=True,
                        upload_to=apps.core.utils.homepage_section_upload_path,
                        validators=[apps.core.validators.validate_ad_banner],
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order on homepage (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this section on homepage"
                    ),
                ),
                (
                    "max_articles",
                    models.PositiveIntegerField(
                        default=6, help_text="Maximum number of articles to display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Articles to display in this section",
                        related_name="homepage_sections",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Section",
                "verbose_name_plural": "Homepage Sections",
                "ordering": ["position", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["section_type", "is_active"],
                        name="core_homepa_section_939c1e_idx",
                    )
                ],
            },
        ),
    ]
