# Generated by Django 4.2.7 on 2026-02-04 08:52

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(
                default="#e74c3c",
                help_text="Primary brand color (hex format, e.g., #e74c3c)",
                max_length=7,
                validators=[apps.core.validators.validate_hex_color],
            ),
        ),
    ]
