# Generated by Django 4.2.7 on 2026-02-03 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakingNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(help_text="Breaking news text", max_length=200),
                ),
                (
                    "urgent",
                    models.BooleanField(
                        default=True, help_text="Mark as urgent (affects display style)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this breaking news item"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Breaking News",
                "verbose_name_plural": "Breaking News",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of name (auto-generated)",
                        unique=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome icon class (e.g., fas fa-newspaper)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                (
                    "article_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of published articles in this category",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Subscriber email address",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Subscription status"),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when subscriber unsubscribed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tag name", max_length=50, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of name (auto-generated)",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Article title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of title (auto-generated)",
                        unique=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief article summary or excerpt", max_length=500
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full article content (supports rich text)"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Article featured/cover image",
                        null=True,
                        upload_to="articles/featured/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "is_breaking",
                    models.BooleanField(
                        default=False, help_text="Mark as breaking news"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Feature on homepage"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of article views"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="Publication date and time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Article author",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="users.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Article category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="news.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Article tags for classification",
                        related_name="articles",
                        to="news.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment text", max_length=1000),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Moderator approval status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article being commented on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="news.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who posted the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article"], name="news_commen_article_a19c9c_idx"
                    ),
                    models.Index(
                        fields=["is_approved"], name="news_commen_is_appr_67abdb_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="news_articl_slug_869c04_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status"], name="news_articl_status_a95c4c_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category"], name="news_articl_categor_ac462d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_featured"], name="news_articl_is_feat_0df2de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_breaking"], name="news_articl_is_brea_cfd84b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-published_at"], name="news_articl_publish_62720b_idx"
            ),
        ),
    ]
