# Generated by Django 4.2.7 on 2026-02-03 17:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(
                help_text="Full article content (supports rich text)"
            ),
        ),
    ]
