# Generated by Django 4.2.7 on 2026-02-03 18:59

import apps.core.utils
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_article_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakingNewsBanner",
            fields=[],
            options={
                "verbose_name": "Breaking News Banner",
                "verbose_name_plural": "Breaking News Banners",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("news.breakingnews",),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Article featured/cover image",
                null=True,
                upload_to=apps.core.utils.article_image_upload_path,
                validators=[apps.core.validators.validate_article_image],
            ),
        ),
    ]
