# Generated by Django 4.2.7 on 2026-02-03 20:16

import apps.core.utils
import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("news", "0003_breakingnewsbanner_alter_article_featured_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Video title", max_length=300)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of title (auto-generated)",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Video description"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Video thumbnail image",
                        null=True,
                        upload_to=apps.core.utils.article_image_upload_path,
                        validators=[apps.core.validators.validate_article_image],
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="YouTube, Vimeo, or other video URL", max_length=500
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        default="00:00",
                        help_text="Video duration (e.g., 12:45)",
                        max_length=20,
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, help_text="Number of views"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this video on homepage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show/hide video"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Publication date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update date"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Video author/uploader",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="users.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Video category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="news.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="news_video_publish_4add3c_idx"
                    ),
                    models.Index(fields=["slug"], name="news_video_slug_69934e_idx"),
                    models.Index(
                        fields=["is_active"], name="news_video_is_acti_e394b1_idx"
                    ),
                ],
            },
        ),
    ]
