# Generated by Django 4.2.7 on 2026-02-04 04:09

import apps.core.utils
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_add_video_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Category icon image",
                null=True,
                upload_to=apps.core.utils.category_icon_upload_path,
                validators=[apps.core.validators.validate_category_icon],
            ),
        ),
    ]
