# Generated by Django 4.2.7 on 2026-02-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_category_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#3b82f6",
                help_text="Category color in hex format (e.g., #3b82f6)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this category is active and visible"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order (lower numbers appear first)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category (leave blank for main category)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="news.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(help_text="Category name", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("parent", "name")},
        ),
    ]
